fix: dawarich build/startup for v1 - make sure "foreman" is installed during build and available during runtime

diff --git a/docker-images/dawarich/Dockerfile b/docker-images/dawarich/Dockerfile
--- a/docker-images/dawarich/Dockerfile
+++ b/docker-images/dawarich/Dockerfile
@@ -11,8 +11,15 @@ RUN mkdir -p '/homelab/original/var/app/db' && \
     cp -R '/var/app/db/.' '/homelab/original/var/app/db' && \
     rm -rf '/var/app/db' && \
     cd /var/app && \
-    bundle install --with development && \
-    bundle exec foreman --version && \
+    (test -d '/var/app/vendor/bundle/ruby/3.4.0' || (printf 'Ruby directory not found.\n' >&2; exit 1)) && \
+    export PATH="/var/app/vendor/bundle/ruby/3.4.0/bin:${PATH}" && \
+    export BUNDLE_PATH="/var/app/vendor/bundle/ruby/3.4.0/gems" && \
+    bundle config set --local without 'test' && \
+    bundle config set --local with 'development' && \
+    bundle add 'prometheus_exporter' --skip-install && \
+    bundle install && \
+    bundle exec 'foreman' --version && \
+    bundle exec 'prometheus_exporter' --help >/dev/null && \
     find './vendor/bundle/ruby' -path '*.*.*/cache/*.gem' -prune -exec rm -rf {} \; && \
     rm -rf './tmp/cache'
 
@@ -62,9 +69,9 @@ COPY --from=prefinal --chown=homelab:homelab /home/homelab /home/homelab
 COPY --from=prefinal --chown=homelab:homelab /homelab /homelab
 RUN rm -rf /var/app
 COPY --from=prefinal --chown=homelab:homelab /var/app /var/app
-ENV PATH="/var/app/vendor/bundle/ruby/3.4.0/bin:${PATH}" \
-    APPLICATION_PROTOCOL="http" \
+ENV APPLICATION_PROTOCOL="http" \
     BACKGROUND_PROCESSING_CONCURRENCY="10" \
+    BUNDLE_PATH="/var/app/vendor/bundle/ruby/3.4.0/gems" \
     DATABASE_HOST="postgis" \
     DATABASE_NAME="database" \
     DATABASE_USERNAME="postgres" \
@@ -72,6 +79,7 @@ ENV PATH="/var/app/vendor/bundle/ruby/3.4.0/bin:${PATH}" \
     HOMELAB_CONTAINER_NAME="dawarich" \
     HOMELAB_CONTAINER_VARIANT="default" \
     MIN_MINUTES_SPENT_IN_CITY="60" \
+    PATH="/var/app/vendor/bundle/ruby/3.4.0/bin:${PATH}" \
     PROMETHEUS_EXPORTER_ENABLED="true" \
     PROMETHEUS_EXPORTER_HOST="0.0.0.0" \
     PROMETHEUS_EXPORTER_PORT="9394" \
