feat: clone dotfiles in all servers

diff --git a/ansible/playbooks/setup-server.yml b/ansible/playbooks/setup-server.yml
--- a/ansible/playbooks/setup-server.yml
+++ b/ansible/playbooks/setup-server.yml
@@ -643,3 +643,57 @@
         if [ "$before_sha" != "$after_sha" ]; then
           printf 'CHANGED\n'
         fi
+
+    ## Dotfiles repository ##
+
+    # TODO: Change to builtin git task
+    - name: Git clone dotfiles
+      register: git_clone_dotfiles
+      changed_when: "'CHANGED' in git_clone_dotfiles.stdout"
+      ansible.builtin.shell: |
+        set -eufo pipefail
+        source "$HOME/.profile"
+
+        if [ ! -e "$HOME/git/dotfiles" ]; then
+          mkdir -p "$HOME/git"
+          git clone 'https://github.com/matejkosiarcik/dotfiles.git' "$HOME/git/dotfiles"
+          printf 'CHANGED\n'
+        fi
+
+    - name: Update dotfiles repository
+      register: update_git_dotfiles
+      changed_when: "'CHANGED' in update_git_dotfiles.stdout"
+      ansible.builtin.shell: |
+        set -eufo pipefail
+        source "$HOME/.profile"
+
+        if [ -d "$HOME/git/dotfiles" ]; then
+          cd "$HOME/git/dotfiles"
+        else
+          printf 'Directory ~/git/dotfiles not found\n'
+          exit 1
+        fi
+
+        if [ "$(git branch --show-current)" != main ]; then
+          git checkout main
+          printf 'CHANGED\n'
+        fi
+
+        if [ "$(git status --short)" != '' ]; then
+          git checkout .
+          git clean -df
+          printf 'CHANGED\n'
+        fi
+
+        if [ "$(git status --short)" != '' ]; then
+          git checkout .
+          git clean -df
+          printf 'CHANGED\n'
+        fi
+
+        git fetch
+
+        if [ "$(git diff --name-only origin/main)" != '' ]; then
+          git pull --ff-only
+          printf 'CHANGED\n'
+        fi
