ci: debug new build job

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -55,7 +55,7 @@ jobs:
         run: |
           printf 'Building %s\n' "${{ matrix.label }}"
           if [ ! -d "${{ matrix.path }}" ]; then
-            printf 'App %s not found.\n' ${{ matrix.path }}" >&2
+            printf 'App %s not found.\n' "${{ matrix.path }}" >&2
             exit 1
           fi
 
