ci: improve build job

diff --git a/.github/workflows/docker-build.yml b/.github/workflows/docker-build.yml
--- a/.github/workflows/docker-build.yml
+++ b/.github/workflows/docker-build.yml
@@ -17,27 +17,45 @@ jobs:
         with:
           persist-credentials: false
 
-      - name: Discover app directories
+      - name: Discover docker apps
         id: discovery
-        shell: bash
         run: |
           set -euf
-          docker_apps="$(find . -type d -path './servers/*/docker-apps/*' | sed 's~^~"~;s~$~"~' | tr '\n' ',')"
-          printf 'matrix=[%s]' "$docker_apps" | tee -a "$GITHUB_OUTPUT"
+
+          tmpfile="$(mktemp)"
+          trap 'rm -f "$tmpfile"' EXIT HUP INT TERM
+
+          find . -type d -path './servers/*/docker-apps/*' -mindepth 4 -maxdepth 4 | while read -r path; do
+            server_name="$(basename "$(dirname "$(dirname "$path")")")"
+            app_name="$(basename "$path")"
+            app_label="$server_name - $app_name"
+            app_path="$path"
+            matrix_json="{\"path\":\"$app_path\",\"label\":\"$app_label\"},"
+          done
+
+          printf 'matrix=[%s]\n' "$(cat "$tmpfile" | sed 's~,$~~')" | tee -a "$GITHUB_OUTPUT"
 
   build:
-    name: Build - ${{ matrix.app }}
+    name: Build - ${{ matrix.label }}
     runs-on: ubuntu-latest
     needs: discovery
     strategy:
       fail-fast: false
       matrix:
-        app: ${{ fromJSON(needs.discovery.outputs.matrix) }}
+        include: ${{ fromJSON(needs.discovery.outputs.matrix) }}
     steps:
       - name: Checkout
         uses: actions/checkout@v7.0.1
         with:
           persist-credentials: false
+
+      - name: Log
+        run: |
+          printf 'Building %s\n' "${{ matrix.label }}"
+          if [ ! -d "${{ matrix.path }}" ]; then
+            printf 'App %s not found.\n' ${{ matrix.path }}" >&2
+            exit 1
+          fi
 
       - name: Install APT dependencies
         run: sudo apt-get update && sudo apt-get install --yes moreutils
@@ -64,30 +82,25 @@ jobs:
           sudo apt-get install --yes --no-install-recommends --no-install-suggests apache2-utils moreutils
           npm install -g @go-task/cli
 
-      - name: Log
-        run: |
-          echo "Building ${{ matrix.app }}"
-          test -d "${{ matrix.app }}"
-
       - name: Setup secrets
         env:
           PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1
-        working-directory: ${{ matrix.app }}
+        working-directory: ${{ matrix.path }}
         run: |
           task secrets -- --mode dev --offline
 
       - name: Docker build
-        working-directory: ${{ matrix.app }}
+        working-directory: ${{ matrix.path }}
         run: |
           task build -- --mode dev
 
       - name: Docker start
-        working-directory: ${{ matrix.app }}
+        working-directory: ${{ matrix.path }}
         run: |
           task start -- --mode dev --dry-run
 
       - name: Docker stop
-        working-directory: ${{ matrix.app }}
+        working-directory: ${{ matrix.path }}
         run: |
           task stop -- --mode dev --dry-run
 
